### ISSUE TITLE
Reset button after completion

### ISSUE THREAD

**Issue by vnihoul77** [koddr/sweetconfirm.js#79]
Hi!
Is there a way to reset the button once completed?

Because there's actually an issue where once completed, when the button is pressed, the hold text (question) is still appearing but it never trigger the timeout.

Is there some solutions to that?

**Comment by koddr** [comment]
Hi,

I don't really understand the context of the question. Please write more input and what do you want to do?

**Comment by vnihoul77** [comment]
After the button is clicked, it won't block the press or reset to the initial state 
https://user-images.githubusercontent.com/4152545/137152434-90ecdacc-bb63-46d4-b362-a77e1651cda1.mp4

**Comment by koddr** [comment]
Hm... It looks more like a tap feature in the mobile version of Google Chrome. On the desktop, when you release the button, it immediately triggers a state reset.

If you can, send a PR that fixes it.

**Comment by vnihoul77** [comment]
No, I have the same on desktop, it never reset to the initial state.
And I don't know either how to fix it :(

**Comment by timpanzee-alt** [comment]
Bumping this, reset would be killah!

**Comment by vnihoul77** [comment]
Yes! Definitely




Le mer. 16 mars 2022 à 03:53, timpanzee-alt ***@***.***> a
écrit :

**Comment by vnihoul77** [comment]
Up
